### ISSUE TITLE
Software: Clash with system theme

### ISSUE THREAD

**Issue by rileyhawk1417** [rdswift/picard-docs#120]
### Type of change requested

- [x] Bug Report
- [ ] Enhancement Request
- [ ] Other

### What you would like to see changed

Hi love the work you guys are doing. Is it possible to make a custom theme editor for Picard?

Had to set the theme inside Picard to default because it was clashing with my custom system theme on Pop OS 20.04 LTS, whenever I want to pick a local cover art I couldn't see the directory properly. Could the bug be the caused due to a snap installation?

### Additional context

The screenshot is below had to use the browser for black screen
![file_picker_2021-07-26_15-36](https://user-images.githubusercontent.com/42723553/126998523-b8bb772c-36d6-4b19-8d43-9c14b549331d.png)
.

**Comment by phw** [comment]
Hi, thanks for reaching out. Picard issues should be posted to https://tickets.metabrainz.org/projects/PICARD/ though, this here is really just for the documentation. Or maybe discussed at https://community.metabrainz.org/c/picard/ if it is more kind of a support issue.

Regarding themes Picard uses the Qt5 theme. The only officially supported one is the default "Fusion" theme, which will be used if you set the theme setting to default. If you set it to "System" it uses your local theme, whatever that is.

Having said this I'm not entirely sure about the issue, the screenshot does not really make it clear to me what is wrong. Can you maybe share a screenshot of Picard how it looks like with your custom theme? As I said, we officially only support the Fusion theme (mainly because we are a small team, and theming issues can be endless), but maybe whatever needs to be done to fix the issue you have helps dark themes in general.

> Could the bug be the caused due to a snap installation?

Definitely possible. Snap apps don't have full access to your locally installed themes, so things don't fully behave as maybe expected. Especially with custom themes. But to be honest I don't know the exact details currently.

**Comment by rileyhawk1417** [comment]
Thanks for answering.
 
I guess will just reinstall using a different method,  let me try and use the desktop wallpaper to try and explain what I mean.

![picard_2_2021-07-27_14-41](https://user-images.githubusercontent.com/42723553/127155594-9f26783b-8772-4b94-a483-c7b57d837c2c.png)

When trying to pick a cover art for the folder I am working with I don't know why but the directory window/file picker just turns transparent. This happens when I select it to follow the system theme, which I would have customized currently am using [Orchis Dark Orange Compact](https://github.com/vinceliuice/Orchis-theme). It doesn't seem to have a problem with the original OS theme Pop OS Light is it because they could be using the same libraries?

**Comment by phw** [comment]
Ah, funny issue :) I guess the same also happens if you use the "Add Folder" or "Add Files" buttons?

So for some background: By default when you open a file picker the file picker from your system is being used, depending on the desktop environment. This is either the one from Gtk or from Qt. In your case it is the Gtk file picker I think (going by the displayed sidebar icons). So this is some issue with Gtk themes, and I bet it is caused by the Snap.

The Snap has access to some common Gtk themes, that's why Pop OS works. But since Gtk themes are dependent on the Gtk version your local Orchis theme likely is incompatible with the Gtk version inside the Snap. I wonder why it is using it at all, I would have expected it to fall back to some default :( Not sure, maybe this can be fixed. Snaps and themes is really awkward stuff.

I have one workaround for you: In Picard Options > User interface enable "Allow selection of multiple directories". This will force the use of Qt's default file picker, and I think this should look better.

**Comment by rileyhawk1417** [comment]
Well am not really fussy about it just thought it would be worth mentioning :) , but thanks for hearing me out. I usually avoid snap packages because they sometimes need a lot of attention when configuring to system libraries lol.

**Comment by rileyhawk1417** [comment]
Hi its definitely an issue with snap installation. Used ppa installation this time and had no fuss with the UI.

![ppa_2021-07-29_00-55](https://user-images.githubusercontent.com/42723553/127406748-a8ec4f8f-1e25-432c-a9aa-12828012576e.png)
