### ISSUE TITLE
Switch translation away from Transifex

### ISSUE THREAD

**Issue by Sophist-UK** [rdswift/picard-docs#35]
**Describe the bug**
IMO transifex is **not** suitable for translating documentation as it is snippet based whilst documentation is very contextual.

IMO the best way to translate a page is to use Google / Yandex / Bing Translate for each page to translate the text, then for an editor to make the text fully coloquial, then recreate any screen-shots in Picard using the same language for both Picard and for example albums / tracks.  

This may need substantial changes made to both the structure of the repo and the structure of the resulting web site.

**Comment by rdswift** [comment]
The way that gettext splits up the page contents for translation is by paragraph, which allows for translation in context.  For example, the translation template file the current Contributing page looks like:

-------

#: ../../source/contributing.rst:7
msgid "Contributing to the Project"
msgstr ""

#: ../../source/contributing.rst:12
msgid "This document only exists because of the volunteer effort that went into its development, from the initial documentation on the Picard website, the information posted in the Community Discussion Forum, documentation from scripts, plugins and program source code, proofreaders, editors, translators, and feedback from the user community."
msgstr ""

#: ../../source/contributing.rst:17
msgid "Further high quality contributions are welcomed from all Picard users wanting to be part of the open source community that creates and maintains this valuable music tool. Even if you cannot write code, based on your experience of using Picard any help you can give to improve this documentation further will be most appreciated.  Even if you cannot improve the existing help, if you can create or maintain translations into other languages, that would be of great benefit."
msgstr ""

#: ../../source/contributing.rst:23
msgid "If you notice an error in the documentation or have additional material to contribute, please `raise an issue <https://github.com/rdswift/picard-docs/issues>`_ on the `documentation project on GitHub <https://github.com/rdswift/picard-docs/>`_.  `Pull Requests <https://github.com/rdswift/picard-docs/pulls>`_ to address outstanding issues are also appreciated."
msgstr ""

#: ../../source/contributing.rst:31
msgid "`Contributing to MusicBrainz Picard <https://github.com/metabrainz/picard/blob/master/CONTRIBUTING.md>`_ / `Picard Translations <https://github.com/metabrainz/picard/blob/master/po/README.md>`_ / `Contributing to the Documentation <https://github.com/rdswift/picard-docs/blob/master/.github/CONTRIBUTING.md>`_"
msgstr ""

-------

The lines starting with an octothorpe are comments indicating the file name and line number of the content.  The `msgid` lines show the content to be translated, and provide the unique ID for the translation item.  The `msgstr` line contains the translation for the ID.  This allows for a bit of flexibility in providing localized colloquial translations.

There is nothing requiring that translations be done using Transifex.  They can be done locally using tools such as Poedit, or even an ordinary text editor using services like Google Translate if desired.  I've started doing initial translations into French locally using Google Translate, but is a slow process because I don't speak French so I have to translate from English to French, and then translate back into English to make sure that the output still makes sense.  When Sphinx builds the output files, it looks for a translation for each of the text IDs found and does a simple replacement for the target output language.  It also handles some standard text such as section and chapter numbering and dates automatically based on the Babel module (I think).

**Comment by Sophist-UK** [comment]
It sounds very cumbersome to use - and unless the URLs for screen shots are translatable too, it doesn't allow for e.g. french versions of screen shots. It would IMO be a whole lot more friendly to simply have french versions of the pages. You take the RST file, paste it into Google Translate, copy the translation and paste it into your editor. Then you tweak the picture URLs and tweak the text and you are done.

With Transifex as described above, it seems like you cannot see the end result page without waiting for the web site to be built. It's simply doesn't sound user friendly to me.

**Comment by phw** [comment]
@Sophist-UK Just translating the entire page won't scale. You can't keep track of changes, can't utilize translation memory and concordance search etc.

Segmentation of the content is the common approach when translating technical documentation. I'm not the biggest fan of Transifex, but I think the general approach is fine and going with Transifex for now works for me.

**Comment by phw** [comment]
Btw, why is this ticket called switch translation away from Transifex? I thought we don't have the translation on Transifex yet, or did I miss something?

**Comment by Sophist-UK** [comment]
We probably need to add image URLs to transifex as well then so that they can be translated to the URLs for the equivalent in other languages.

**Comment by rdswift** [comment]
> I thought we don't have the translation on Transifex yet, or did I miss something?

We don't have them on Transifex yet.  I wasn't sure about adding a repository under my account to the MetaBrainz account on Transifex, and I also want to make sure that I have the file structure pretty much finalized.  I'm in the process of restructuring everything so that it works properly and can be served from ReadTheDocs.

**Comment by rdswift** [comment]
> We probably need to add image URLs to transifex as well then so that they can be translated to the URLs for the equivalent in other languages.

I'm still looking into how this can be done.  I haven't found an acceptable method yet.

**Comment by rdswift** [comment]
> We probably need to add image URLs to transifex as well then so that they can be translated to the URLs for the equivalent in other languages.

**UPDATE:**

In going through the Sphinx documentation again, I found the solution, and it is so simple.  All you need to do is save the language-specific image in the same directory as the default image, and add a dot and the language code just before the extension.  For example, if the default image is `default_image.png` then the image served for the French translation will be `default_image.fr.png` if it exists, otherwise the default image will be served.  The image specified in the RST file would still be `default_image.png` and Sphinx will automatically change it if required when producing the html (or pdf or epub) output files.  No need to do anything in terms of editing links in the translation (\*.po) files.
